"""add region field in country table

Revision ID: 642743956608
Revises: 9d54be5c0995
Create Date: 2024-09-27 08:42:23.562476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642743956608'
down_revision = '9d54be5c0995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_column('region')

    # ### end Alembic commands ###
